color: null
description: null
fieldLayouts:
  a83f4c2e-3f08-45ca-8327-c0bca7ed8469:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-03T11:09:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c762b8ff-4dd7-4341-bfc8-52ef7c09d6fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T11:11:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62083fb6-1a8c-49b9-9782-374ce3b3a7c8 # Rich Text (Basic)
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69c48fde-a3dc-46c7-9baf-d2eb4e705f05
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e553f6d-ed02-43e1-8c7d-b5952f2ae4ea
        userCondition: null
handle: accordionItem
hasTitleField: true
icon: plus
name: 'Accordion Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
