color: null
description: null
fieldLayouts:
  4efd34c5-3a38-41bf-b786-abc70a107dfd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-04T10:01:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aff5ab29-35f9-43c1-bfc1-8419394f1987 # Text Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0e52d68-88fa-4c89-863d-df3d2f192f56
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-04T09:52:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 03a2afff-8e7c-45e2-8078-c71d1ac627a3 # Content Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67700efd-781c-45ca-a7df-b55eaab154fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 845fa8fc-3048-46a4-b488-595285e1a468
        userCondition: null
handle: contentCards
hasTitleField: false
icon: cards-blank
name: 'Content Cards'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
