color: null
description: null
fieldLayouts:
  63f9e194-cd3c-4752-ac5b-2c1c973eece8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-04T11:12:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c4c0a8f3-12eb-4794-8712-aee10efa4060
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-04T11:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9f5b927-df42-44aa-9851-28659f875ab1 # Entry Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27d2f170-54e2-4a46-a08c-51491d423173
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a1f8344a-c862-4757-ad8c-ec0077daaa53
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-04T11:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 948057e1-04f5-43cb-8a4d-43e67384f5eb # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0852466c-3990-486e-94a2-b9f6e852711a
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 46ac4643-2eba-4088-a037-1eb0f00f21aa
        userCondition: null
handle: index
hasTitleField: true
icon: list-tree
name: Index
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
