color: null
fieldLayouts:
  62767917-9438-4429-a8a3-8a2938c3f86e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-23T14:36:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ea252716-954a-4e85-b183-4852be96df43 # Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54a17121-4f87-4293-8897-f48da62dcdeb
            userCondition: null
            warning: null
            width: 100
        name: Tags
        uid: 6298d91d-38cb-4b99-8310-c0932d994e0f
        userCondition: null
handle: meta
hasTitleField: false
icon: null
name: Meta
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
