color: null
description: null
fieldLayouts:
  e6dc4fc6-0717-4da6-815b-2807d41d672a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-03T10:26:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 294fa98b-19c0-40ee-80b0-8a4fcf868b47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T10:29:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d0c7900e-d61c-4839-a59e-70bb47358360 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 704c1a49-2a62-406b-bda7-aa88d7043f79
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T10:29:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f01ab0c4-931a-46aa-bcec-67b6c6941e21 # Plain Text
            handle: person
            includeInCards: false
            instructions: null
            label: Person
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 050cf8ac-e318-41ab-9a6d-a23787408d47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T10:29:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f01ab0c4-931a-46aa-bcec-67b6c6941e21 # Plain Text
            handle: company
            includeInCards: false
            instructions: null
            label: Company
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80840031-9ca9-40a4-b935-82a5f88c0104
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-03T10:29:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62083fb6-1a8c-49b9-9782-374ce3b3a7c8 # Rich Text (Basic)
            handle: testimonial
            includeInCards: false
            instructions: null
            label: Testimonial
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: defa3206-895c-47f4-9dda-8a9dc02fa390
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c527634f-53b5-428d-80f5-009934c39953
        userCondition: null
handle: testimonial
hasTitleField: true
icon: comment-heart
name: Testimonial
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
