color: null
description: null
fieldLayouts:
  4183031b-ab39-4c03-be64-1c884c571924:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-03T13:58:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6987f99c-8b2a-479a-a63e-51df68e0f21a # Rich Text (Full)
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a558bedf-bc3d-4e84-8386-b268de1abd28
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c44b07da-4fac-45e9-ac58-c0f9455b0c04
        userCondition: null
handle: text
hasTitleField: false
icon: text
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
