cardThumbAlignment: end
tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-01-23T11:25:25+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\UsernameField
        uid: bcc986e9-e4ae-4ae0-9221-7e1361f861a8
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-01-23T11:25:25+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: 4b517ceb-d88e-46f4-9d96-b5b6a61aaab3
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-01-23T11:25:25+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: 30571d3d-1cfa-4344-a13f-5921f725ea3b
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-01-23T11:25:25+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: 5fb2f497-b2f4-4c34-abf2-50f29583f331
        userCondition: null
        width: 100
      -
        dateAdded: '2025-07-04T14:45:55+00:00'
        editCondition: null
        elementCondition: null
        fieldUid: f01ab0c4-931a-46aa-bcec-67b6c6941e21 # Plain Text
        handle: role
        includeInCards: false
        instructions: null
        label: Role
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 4acfbe03-1e7e-4b5d-a8df-7b74827e87df
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: a26dd05d-04a9-4a64-975c-543955879821
    userCondition: null
