columnSuffix: null
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: false
settings:
  createButtonLabel: 'New content block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 16e5b50d-e7a4-46d7-b51f-084d25a1e36b # Hero
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - cac24c58-8d46-48c3-98bd-d99f03d7c8ef # Section
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7d44415b-35cb-4e25-bf4f-9ef55eb90547 # Anchor
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 0b321564-e4b7-4cad-990a-990f27e2bc26 # Spacer
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
