columnSuffix: null
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: false
settings:
  createButtonLabel: 'New block'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 2257efc6-f010-4dd9-997b-95a89fa4c2d3 # Divider
    -
      __assoc__:
        -
          - uid
          - 6d2baf55-d7b9-4e8f-bb2d-f91dba9a5dee # Text
    -
      __assoc__:
        -
          - uid
          - 1b69a2ba-578a-4016-a46c-2bb3c40f8c91 # Text Elements
    -
      __assoc__:
        -
          - uid
          - 1cc3e83c-680b-483a-9d51-c2d6de10221b # Text & Media
    -
      __assoc__:
        -
          - uid
          - 0b321564-e4b7-4cad-990a-990f27e2bc26 # Spacer
    -
      __assoc__:
        -
          - uid
          - 7d44415b-35cb-4e25-bf4f-9ef55eb90547 # Anchor
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
