columnSuffix: null
handle: contentBlock
instructions: null
name: 'Content Block'
searchable: false
settings:
  createButtonLabel: 'New content block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 274bbd5f-3859-4d8f-91c3-f68ebbb29720 # Columns
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2257efc6-f010-4dd9-997b-95a89fa4c2d3 # Divider
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 89b0ee7b-1530-4b52-9ba3-1335bc1eaf8e # FAQs
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7e20247b-253f-4e4b-a04f-a66573c4a529 # Image
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 6d2baf55-d7b9-4e8f-bb2d-f91dba9a5dee # Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 1b69a2ba-578a-4016-a46c-2bb3c40f8c91 # Text Elements
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 1cc3e83c-680b-483a-9d51-c2d6de10221b # Text & Media
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 21500d84-7ee2-479d-93db-750c756557cd # Video
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - c23595e5-62be-4f04-b180-0411df260b64 # Showcase
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - adf4e920-a376-49f3-8733-3733051a3f4c # CTA
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2ee8ad4c-a735-4992-8ea3-b6e2d0930377 # Logos
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 77018bc1-5b35-451b-b35c-46a2d4e451aa # Steps
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 4d109d67-14c0-415f-aca1-42cac4c6640c # Form
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7b04b850-94c5-4f5f-8689-a5a2c5c17e18 # Content Cards
        -
          - group
          - General
  includeTableView: false
  maxEntries: 1
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
