columnSuffix: null
handle: hyperlink
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - target
    - urlSuffix
    - rel
    - ariaLabel
    - download
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - singles
                - 'section:f70322ae-4170-462e-b3f4-138012e301da' # Pages
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
    - category
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
