columnSuffix: null
handle: hyperlink
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - target
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - entry
    - url
    - category
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
