columnSuffix: null
handle: maximumWidth
instructions: null
name: 'Maximum Width'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - none
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Contain
        -
          - value
          - contain
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - XS
        -
          - value
          - xs
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - SM
        -
          - value
          - sm
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - MD
        -
          - value
          - md
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - LG
        -
          - value
          - lg
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - XL
        -
          - value
          - xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2XL
        -
          - value
          - 2xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3XL
        -
          - value
          - 3xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4XL
        -
          - value
          - 4xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 5XL
        -
          - value
          - 5xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 6XL
        -
          - value
          - 6xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 7XL
        -
          - value
          - 7xl
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
