columnSuffix: null
handle: paragraph
instructions: null
name: Paragraph
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: ed206a6f-5783-44ef-851d-fb1166bc3102 # Paragraph
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
