columnSuffix: null
handle: richTextFull
instructions: null
name: 'Rich Text (Full)'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
    - 4
    - 5
    - 6
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
    - '|'
    - bulletedList
    - numberedList
    - '|'
    - horizontalLine
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
