columnSuffix: null
contentColumnType: string
fieldGroup: c18afe66-b83b-45ea-ab40-89602795ee45 # Meta
handle: scripts
instructions: null
name: Scripts
searchable: false
settings:
  contentTable: '{{%matrixcontent_scripts}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
