columnSuffix: null
handle: socialNetwork
instructions: null
name: 'Social Network'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Bluesky
        -
          - value
          - bluesky
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Facebook
        -
          - value
          - facebook
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Instagram
        -
          - value
          - instagram
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - LinkedIn
        -
          - value
          - linkedin
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - TikTok
        -
          - value
          - tiktok
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Twitch
        -
          - value
          - twitch
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - WhatsApp
        -
          - value
          - whatsapp
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - X
        -
          - value
          - x
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
