dateModified: 1737643395
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:f70322ae-4170-462e-b3f4-138012e301da' # Pages
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
email:
  fromEmail: dev@clubstudio.co.uk
  fromName: 'Craft CMS'
  replyToEmail: null
  template: null
  transportSettings:
    host: $SMTP_HOSTNAME
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    2b8d277c-c134-499a-bb5b-11c2bec12bb1: Basic # Basic
    4f9a3e6f-6b6c-44af-b349-367f62ef9286: Meta # Meta
    84f8b614-1005-47ab-8c38-5436ca169550: 'Public Schema' # Public Schema
    326377be-c2da-462e-bea3-4eb8ca886573: 'Tag Position' # Tag Position
    948057e1-04f5-43cb-8a4d-43e67384f5eb: SEO # SEO
    b1d95554-25a7-42c3-822d-09155f628a4b: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    d6b7a87c-df19-4865-b62e-756d2cfc9271: Simple # Simple
    d14159c6-01c5-410d-b1c8-785d25b4027f: Tag # Tag
    e14f5323-5bc2-40b2-8feb-9b811c97394c: Code # Code
    ea252716-954a-4e85-b183-4852be96df43: Tags # Tags
    f70322ae-4170-462e-b3f4-138012e301da: Pages # Pages
    fd532b74-9e46-4921-867f-79a80ef26fdf: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: SX7RCYTZQEOZDNSAISS2QATL
    schemaVersion: 2.1.0
  retour:
    edition: standard
    enabled: true
    licenseKey: TEQULDJKB6QJ3N4UJR8CXZIW
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 6J4D1LE2U8LDFKEJDVAAG5TW
    schemaVersion: 3.0.12
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: 'Craft CMS'
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/London
