dateModified: 1737640259
email:
  fromEmail: dev@clubstudio.co.uk
  fromName: 'Craft CMS'
  replyToEmail: null
  template: null
  transportSettings:
    host: $SMTP_HOSTNAME
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    84f8b614-1005-47ab-8c38-5436ca169550: 'Public Schema' # Public Schema
    948057e1-04f5-43cb-8a4d-43e67384f5eb: SEO # SEO
    b1d95554-25a7-42c3-822d-09155f628a4b: 'Craft CMS' # Craft CMS
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    fd532b74-9e46-4921-867f-79a80ef26fdf: 'Craft CMS' # Craft CMS
plugins:
  navigation:
    edition: standard
    enabled: true
    licenseKey: SX7RCYTZQEOZDNSAISS2QATL
    schemaVersion: 2.1.0
  retour:
    edition: standard
    enabled: true
    licenseKey: TEQULDJKB6QJ3N4UJR8CXZIW
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 6J4D1LE2U8LDFKEJDVAAG5TW
    schemaVersion: 3.0.12
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: 'Craft CMS'
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/London
