dateModified: 1745415537
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:f70322ae-4170-462e-b3f4-138012e301da' # Pages
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
email:
  fromEmail: dev@clubstudio.co.uk
  fromName: 'Craft CMS'
  replyToEmail: null
  template: null
  transportSettings:
    host: $SMTP_HOSTNAME
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0b321564-e4b7-4cad-990a-990f27e2bc26: Spacer # Spacer
    1b69a2ba-578a-4016-a46c-2bb3c40f8c91: 'Text Elements' # Text Elements
    1cc3e83c-680b-483a-9d51-c2d6de10221b: 'Text & Media' # Text & Media
    2b8d277c-c134-499a-bb5b-11c2bec12bb1: Basic # Basic
    2debe9c4-8aef-459d-94e1-8490bd05cc6f: New # New
    3e21768c-5b31-4bba-be9f-8341e29cc796: Heading # Heading
    3ed91472-4973-4997-8a82-57e4ff827e6e: Link # Link
    3f23d659-bee2-453e-b674-c4f730be7e88: 'Profile URL' # Profile URL
    4c1e65ea-bd76-45a2-9b25-2e7d92a12ff0: Link # Link
    4d109d67-14c0-415f-aca1-42cac4c6640c: Form # Form
    4e472aae-8399-4bd0-ae02-daf1b837bdfd: 'Content Blocks' # Content Blocks
    5c86e823-c1de-4e1e-a517-7ab40b8724a0: Home # Home
    05fe8308-3bae-4067-ba98-f1ac9bc90dd8: 'Spacer Size' # Spacer Size
    6d2baf55-d7b9-4e8f-bb2d-f91dba9a5dee: Text # Text
    7d44415b-35cb-4e25-bf4f-9ef55eb90547: Anchor # Anchor
    8cb7772d-559f-4262-beae-c26e872282ea: Links # Links
    84f8b614-1005-47ab-8c38-5436ca169550: 'Public Schema' # Public Schema
    145cfe22-19bb-4807-8e33-c8d059374c2c: 'Text Alignment' # Text Alignment
    650c6872-2c55-4840-955f-de309ced444c: 'Contact Form' # Contact Form
    1414d7cb-fb98-4f48-88f2-e5b2401cf402: 'Horizontal Alignment' # Horizontal Alignment
    2257efc6-f010-4dd9-997b-95a89fa4c2d3: Divider # Divider
    3975bba4-34d1-446f-a01c-a3059f621585: 'Social Profile' # Social Profile
    06995b69-1665-4491-b99a-edfe08b151fd: Links # Links
    7397cb77-355d-47eb-83b4-30f061ca415b: 'Vertical Alignment' # Vertical Alignment
    24905e06-d0a8-486d-b05e-2d1128c9230e: 'Social Profiles' # Social Profiles
    198475be-dc00-42d7-8ed4-b48aa2865944: Paragraph # Paragraph
    326377be-c2da-462e-bea3-4eb8ca886573: 'Tag Position' # Tag Position
    761607ea-8c75-4aea-af4a-00d367e51171: 'Heading Level' # Heading Level
    948057e1-04f5-43cb-8a4d-43e67384f5eb: SEO # SEO
    a49385d7-d5af-4d02-a3b0-40a69c749712: Paragraph # Paragraph
    aff5ab29-35f9-43c1-bfc1-8419394f1987: 'Text Content' # Text Content
    b1d95554-25a7-42c3-822d-09155f628a4b: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    b15bb767-c33c-443c-8536-0b08e9e1d3df: Padding # Padding
    c6ba79fe-02b0-4513-a81e-d59a8f5b89b8: Globals # Globals
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    c1874064-cabe-4c03-943f-9af16558b6cf: Globals # Globals
    d6b7a87c-df19-4865-b62e-756d2cfc9271: Simple # Simple
    d363d288-d9a6-466d-82f0-a0fdd9530d71: Form # Form
    d14159c6-01c5-410d-b1c8-785d25b4027f: Tag # Tag
    e2c74420-bbaf-40c8-acf9-daf436a33bbd: 'Maximum Width' # Maximum Width
    e3cda67e-8c3a-4c54-b1d6-0e9468607930: Eyebrow # Eyebrow
    e6b9a7b0-4786-4d98-aa93-e7de2a709e9c: 'Social Network' # Social Network
    e7c39107-95e6-401c-8be7-a07e337fb7b7: 'Rich Text' # Rich Text
    e10b1344-6730-4ebf-b792-fbc2e3a15e04: 'Media Position' # Media Position
    e14f5323-5bc2-40b2-8feb-9b811c97394c: Code # Code
    ea252716-954a-4e85-b183-4852be96df43: Tags # Tags
    ed206a6f-5783-44ef-851d-fb1166bc3102: Paragraph # Paragraph
    f01ab0c4-931a-46aa-bcec-67b6c6941e21: 'Plain Text' # Plain Text
    f70322ae-4170-462e-b3f4-138012e301da: Pages # Pages
    fd532b74-9e46-4921-867f-79a80ef26fdf: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  formie:
    edition: standard
    enabled: true
    schemaVersion: 3.4.8
  navigation:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
  retour:
    edition: standard
    enabled: true
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.12
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: 'Craft CMS'
  retryDuration: null
  schemaVersion: 5.7.0.3
  timeZone: Europe/London
