fieldLayouts:
  2f7cad08-6f13-492f-90cc-217c51232532:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-28T14:36:16+00:00'
            elementCondition: null
            fieldUid: 24905e06-d0a8-486d-b05e-2d1128c9230e # Social Profiles
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b8a5801-54ac-43f2-a8a1-0a1729ee35cc
            userCondition: null
            warning: null
            width: 100
        name: Social
        uid: de9cb6b2-a53e-4c39-8653-e457997e13fa
        userCondition: null
handle: contactInformation
name: 'Contact Information'
sortOrder: 2
