fieldLayouts:
  79a55e35-5679-4dfb-b100-2a8f337f2cf4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-23T14:36:51+00:00'
            elementCondition: null
            fieldUid: ea252716-954a-4e85-b183-4852be96df43 # Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54a17121-4f87-4293-8897-f48da62dcdeb
            userCondition: null
            warning: null
            width: 100
        name: Tags
        uid: 6298d91d-38cb-4b99-8310-c0932d994e0f
        userCondition: null
handle: meta
name: Meta
sortOrder: 1
