defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 09154649-593b-4c0b-aa9b-bba01d18d70e # Article
handle: articles
maxAuthors: null
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fd532b74-9e46-4921-867f-79a80ef26fdf: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/article.twig
    uriFormat: 'articles/{slug}'
type: channel
