defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2b8d277c-c134-499a-bb5b-11c2bec12bb1 # Basic
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fd532b74-9e46-4921-867f-79a80ef26fdf: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry.twig
    uriFormat: __home__
type: single
