defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c1874064-cabe-4c03-943f-9af16558b6cf # Meta
handle: meta
maxAuthors: 1
name: Meta
propagationMethod: all
siteSettings:
  fd532b74-9e46-4921-867f-79a80ef26fdf: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
