defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2b8d277c-c134-499a-bb5b-11c2bec12bb1 # Basic
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fd532b74-9e46-4921-867f-79a80ef26fdf: # Craft CMS
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: aa2499c8-42ee-4fa4-86aa-70f980ed059f
type: structure
