defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: af72e76d-2752-456f-a86c-e9fe22eaaf71 # Testimonial
handle: testimonials
maxAuthors: 1
name: Testimonials
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fd532b74-9e46-4921-867f-79a80ef26fdf: # $CRAFT_SITE_NAME
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: channel
